imports:
    - { resource: @AppBundle/Resources/config/services.yml }

parameters:
#    parameter_name: value

services:
    # Twig Render Status Extension
    app.twig.renderData_extension:
        class: AppBundle\Twig\RenderDataExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
    app.twig.renderSkills_extension:
        class: AppBundle\Twig\RenderSkillsExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
    app.twig.renderSorter_extension:
        class: AppBundle\Twig\RenderSorterExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }