# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    # Twig Render Status Extension
    app.twig.renderData_extension:
        class: AppBundle\Twig\RenderDataExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
    app.twig.renderSkills_extension:
        class: AppBundle\Twig\RenderSkillsExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
    app.twig.renderSorter_extension:
        class: AppBundle\Twig\RenderSorterExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
