parameters:
#    parameter_name: value

services:
    #FOS USER FORM TYPES
    app.change_password.form.type:
        class: AppBundle\Form\Type\ChangePasswordFormType
        arguments: ['@service_container',%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: cls_change_password }
    app.registration.form.type:
        class: AppBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type }
    app.profile.form.type:
        class: AppBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: cls_user_profile }
