AppBundle\Entity\Comment:
    type: entity
    table: comments
    repositoryClass: AppBundle\Repository\CommentRepository
    id:
        id:
            type: integer
            id: true
            nullable: false
            generator:
                strategy: AUTO
    fields:
        rating:
            type: integer
            nullable: false
        comment:
            type: string
            length: '255'
            nullable: false
        status:
            type: smallint
            nullable: false
        dateCreated:
            type: datetime
            nullable: true
            column: date_created
        dateUpdated:
            type: datetime
            nullable: true
            column: date_updated
        dateApproved:
            type: datetime
            nullable: true
            column: date_approved
        locale:
            type: string
            length: '10'
            nullable: true
        ipAddress:
            type: string
            length: '40'
            nullable: true
            column: ip_address
        userAgent:
            type: string
            length: '350'
            nullable: true
            column: user_agent
    manyToOne:
        course:
            targetEntity: AppBundle\Entity\Course
            inversedBy: comments
            cascade: ["persist"]
            joinColumn:
                name: course_id
                referencedColumnName: id
                nullable: false
        user:
            targetEntity: AppBundle\Entity\User
            inversedBy: comments
            cascade: ["persist"]
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: false
    lifecycleCallbacks: {  }
