AppBundle\Entity\CourseTag:
    type: entity
    table: course_tags
    repositoryClass: AppBundle\Repository\CourseTagRepository
    id:
        id:
            type: integer
            id: true
            nullable: false
            generator:
                strategy: AUTO
    fields:
        status:
            type: smallint
            nullable: false
        dateCreated:
            type: datetime
            nullable: true
            column: date_created
        dateUpdated:
            type: datetime
            nullable: true
            column: date_updated
        dateApproved:
            type: datetime
            nullable: true
            column: date_approved
    manyToOne:
        course:
            targetEntity: AppBundle\Entity\Course
            inversedBy: tags
            cascade: ["persist", "remove"]
            joinColumn:
                name: course_id
                referencedColumnName: id
                nullable: false
        tag:
            targetEntity: AppBundle\Entity\Tag
            inversedBy: tags
            cascade: ["persist", "remove"]
            joinColumn:
                name: tag_id
                referencedColumnName: id
                nullable: false
        creator:
            targetEntity: AppBundle\Entity\User
            inversedBy: courseTagsCreator
            cascade: ["persist", "remove"]
            joinColumn:
                name: created_by
                referencedColumnName: id
                nullable: false
        updater:
            targetEntity: AppBundle\Entity\User
            inversedBy: courseTagsUpdater
            cascade: ["persist", "remove"]
            joinColumn:
                name: updated_by
                referencedColumnName: id
                nullable: true
        approver:
            targetEntity: AppBundle\Entity\User
            inversedBy: courseTagsApprover
            cascade: ["persist", "remove"]
            joinColumn:
                name: approved_by
                referencedColumnName: id
                nullable: true
    lifecycleCallbacks: {  }
