AppBundle\Entity\CourseLike:
    type: entity
    table: course_likes
    repositoryClass: AppBundle\Repository\CourseLikeRepository
    id:
        id:
            type: integer
            id: true
            nullable: false
            generator:
                strategy: AUTO
    fields:
        dateCreated:
            type: datetime
            nullable: true
            column: date_created
    manyToOne:
        course:
            targetEntity: AppBundle\Entity\Course
            inversedBy: likes
            cascade: ["persist"]
            joinColumn:
                name: course_id
                referencedColumnName: id
                nullable: false
        user:
            targetEntity: AppBundle\Entity\User
            inversedBy: courseLiker
            cascade: ["persist"]
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: false
    lifecycleCallbacks: {  }
