AppBundle\Entity\PreferenceType:
    type: entity
    table: preference_types
    repositoryClass: AppBundle\Repository\PreferenceTypeRepository
    id:
        id:
            type: integer
            id: true
            nullable: false
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '50'
            nullable: false
        description:
            type: string
            length: '255'
            nullable: true
        status:
            type: smallint
            nullable: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at

        updatedAt:
            type: datetime
            nullable: true
            column: updated_at

    oneToMany:
        preferences:
            targetEntity: AppBundle\Entity\Preference
            mappedBy: preferenceType
            cascade: ["persist", "remove"]
    manyToOne:
        creator:
            targetEntity: AppBundle\Entity\User
            inversedBy: preferenceTypesCreator
            cascade: ["persist"]
            joinColumn:
                name: created_by
                referencedColumnName: id
                nullable: false
        updater:
            targetEntity: AppBundle\Entity\User
            inversedBy: preferenceTypesUpdater
            cascade: ["persist"]
            joinColumn:
                name: updated_by
                referencedColumnName: id
                nullable: true
    lifecycleCallbacks: {  }
