AppBundle\Entity\Tag:
    type: entity
    table: tags
    repositoryClass: AppBundle\Repository\TagRepository
    id:
        id:
            type: integer
            id: true
            nullable: false
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '20'
            nullable: false
        description:
            type: string
            length: '255'
            nullable: true
        status:
            type: smallint
            nullable: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        approvedAt:
            type: datetime
            nullable: true
            column: approved_at
    oneToMany:
        tags:
            targetEntity: AppBundle\Entity\CourseTag
            mappedBy: tag
            cascade: ["persist"]
    lifecycleCallbacks: {  }
