AppBundle\Entity\TransactionAuthor:
    type: entity
    repositoryClass: AppBundle\Repository\TransactionAuthorRepository
    manyToOne:
        course:
            targetEntity: AppBundle\Entity\Course
            inversedBy: authorTransactions
            cascade: ["persist"]
            joinColumn:
                name: course_id
                referencedColumnName: id
                nullable: true
                onDelete: CASCADE
    lifecycleCallbacks: {  }