AppBundle\Entity\Transaction:
    type: entity
    table: transactions
    repositoryClass: AppBundle\Repository\TransactionRepository
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: user_type
        type: string
    discriminatorMap:
        author: AppBundle\Entity\TransactionAuthor
        subscriber: AppBundle\Entity\TransactionSubscriber
        admin: AppBundle\Entity\TransactionAdmin
    id:
        id:
            type: integer
            id: true
            nullable: false
            generator:
                strategy: AUTO
    fields:
        transactionId:
            type: string
            length: '50'
            nullable: false
            column: transaction_id
        type:
            type: integer
            nullable: false
        amount:
            type: float
            nullable: false
            precision: 10
            scale: 2
        balance:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
            options:
                default: '0.00'
        creditDebit:
            type: integer
            nullable: false
            column: credit_debit
        description:
            type: text
            nullable: true
            length: null
            fixed: false
        status:
            type: integer
            nullable: true
            options:
                default: 1
        commissionPercentage:
            type: float
            nullable: true
            precision: '10'
            scale: '2'
            column: commission_percentage
        commissionAmount:
            type: float
            nullable: true
            precision: '10'
            scale: '2'
            column: commission_amount
        dateCreated:
            type: datetime
            column: date_created
        dateUpdated:
            type: datetime
            column: date_updated
    manyToOne:
        user:
            targetEntity: AppBundle\Entity\User
            inversedBy: userTransactions
            cascade: ["persist"]
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: false
        admin:
            targetEntity: AppBundle\Entity\User
            inversedBy: adminTransactions
            cascade: ["persist"]
            joinColumn:
                name: admin_id
                referencedColumnName: id
                nullable: false
    lifecycleCallbacks: {  }
