AppBundle\Entity\TransactionSubscriber:
    type: entity
    repositoryClass: AppBundle\Repository\TransactionSubscriberRepository
    manyToOne:
        subscription:
            targetEntity: AppBundle\Entity\Subscription
            inversedBy: subscriberTransactions
            cascade: ["persist"]
            joinColumn:
                name: subscription_id
                referencedColumnName: id
                nullable: true
                onDelete: CASCADE
    lifecycleCallbacks: {  }